// Per-character parts-sheet contents. Hand-written from each character's
// look, prop, tells and idles in data/characters/*.json.
const MOUTHS = 'frown; angry grimace (teeth clenched); tight-lipped; nervous (pursed, pulled to one side); neutral closed; slight smile; broad smile showing teeth; laughing, wide open; talking "ah"; talking "oh"; talking "ee"; lips pressed together ("m/b/p"); top teeth on lower lip ("f/v")';
export const CLEAR = 'with CLEAR lenses: only the rim and a faint highlight, so the eyes show through';
const EYES = 'looking at the viewer; looking toward the table\'s centre; looking down (at their cards); looking away; wide open; half-closed; narrowed (squinting); closed (blinking)';
export function eyes(desc, extra) {
  return `Eyes${desc ? ` (${desc})` : ''}: each a WHOLE eye, the white, iris and lid drawn together. In three-quarter view the near eye and the far eye differ, so draw BOTH, in each state: ${EYES}${extra ? '; ' + extra : ''}`;
}
export function face(o = {}) {
  return [
    (o.head ?? 'Blank head: skin only, with ears and neck, NO eyes, eyebrows, nose or mouth drawn on it')
      + (o.hair && !/bald/.test(o.head ?? '') ? '. Draw it bald: the hair is a separate piece' : '')
      + '. No collar, shirt or clothing on it: the bare neck ends in a clean V where a collar would sit',
    ...(o.hair ?? []),
    o.brows ?? 'Eyebrows, near and far (they differ in three-quarter view), each in 3 clearly different shapes: neutral; angry (inner end pulled down); worried (inner end pushed up). Raised is done by moving them, so no raised pose',
    o.eyesItem ?? eyes(o.eyes, o.eyesExtra),
    o.nose ?? 'Nose as a separate piece',
    `Mouths, each a separate piece: ${o.mouths ?? MOUTHS}${o.mouthsExtra ? '; ' + o.mouthsExtra : ''}. ${o.beardPatch ? 'The beard in every patch matches the painted beard exactly, so they swap without a join' : 'Each is the MOUTH ONLY (lips, teeth, tongue) cut out on its own: no nose, no chin, no cheeks, no skin around it'}. Same lip and skin colour as the reference. Draw EVERY mouth listed, the unhappy ones too: do not turn them into smiles`,
    ...(o.extra ?? []),
  ];
}
export function body(torso, layers = [], o = {}) {
  return [
    `Torso with NO head and NO arms: ${torso}. Seated, from the shoulders down to the lap, cut off straight well BELOW the waist: the round table's edge covers the bottom, so draw more than will show. Any collar is EMPTY: no neck or mannequin inside it. The sleeves stop at the shoulder: NO forearms or hands anywhere on the torso`,
    ...layers,
    o.upper ?? 'Upper arms (shoulder to elbow), near and far, as separate pieces, in the sleeve',
    o.fore ?? 'Forearms (elbow to wrist, NO hand), near and far, in two angles: lying on the table pointing in toward its centre, and raised. The hand pieces cover their ends',
    ...(o.extra ?? []),
  ];
}
// Card actions get a sheet of their own: eight poses came back complete where
// a longer list lost some.
const CARD = [
  'lifting the corner of a playing card to peek (the card itself NOT drawn)',
  'knuckles rapping the table (checking)',
  'pushing forward, palm and fingers low (as if pushing chips; chips NOT drawn)',
  'open, shoving forward hard (going all in)',
  'flat, sliding sideways (folding cards away)',
  'cupped, raking toward the body (collecting a pot)',
  'fist',
  'turning something over, thumb underneath (showing cards; cards NOT drawn)',
];
const OWN = [
  'flat on the table, relaxed',
  'open palm up (a shrug, or a gesture while talking)',
  'relaxed, fingers loosely curled (idle)',
];
export function hands(desc, extra = [], poses = null) {
  const header = desc.endsWith('.') ? desc.slice(0, -1)
    : `${desc}: each hand WITH its cuff and a short stub of whatever covers the wrist (sleeve, glove cuff, or bare forearm), cut straight across the stub; the forearm piece goes under that stub. Draw each pose ONCE, as the right hand: the game mirrors it for the left`;
  return {
    card: [header, ...(poses ?? CARD).map(p => `Pose: ${p}`)],
    own: poses ? (extra.length ? [header, ...extra] : []) : [header, ...OWN.map(p => `Pose: ${p}`), ...extra],
  };
}

export const PARTS = {
  alice: {
    face: face({ hair: ['Long hair as two separate pieces: the back layer (behind the head) and the front strands', 'Hairband as a separate piece'],
      eyes: 'drawn LARGE and expressive: her face is her tell', eyesExtra: 'very wide with small pupils (startled)',
      mouthsExtra: 'biting her lower lip; a disapproving little frown, as if the cards had been rude' }),
    body: body('a full-skirted dress in deep Victorian blue (NOT powder blue) under a white pinafore', ['Pinafore bib as a separate front layer'], { upper: 'Upper arms in short puffed sleeves, left and right' }),
    hands: hands('Small girl\'s hands', ['Hand holding the little DRINK ME bottle', 'Hand smoothing the pinafore flat']),
    props: ['The little glass bottle with a paper label reading DRINK ME, standing upright', 'The same bottle lying on its side'],
  },
  arthur: {
    face: face({ hair: ['Greying hair as a separate piece', 'Short greying beard as a separate piece'],
      extra: ['Plain gold crown with a visible dent, in 2 angles: sitting straight, and slipped a fraction to one side'] }),
    body: body('broad shoulders in chain mail', ['Red mantle: back layer (behind the shoulders) and front drape as separate pieces']),
    hands: hands('Hands, a king\'s, weathered', ['Hand resting on top of a sword hilt (hilt NOT drawn)', 'Hand raising a cup', 'Fingertip touching (as if rubbing the dent in a crown)']),
    props: ['Excalibur, sheathed, standing upright, hilt at the top (the whole sword and scabbard)', 'A plain drinking cup'],
  },
  astronaut: {
    face: face({ hair: ['Short practical hair as a separate piece'], mouthsExtra: 'a grin she is trying to hide (lips pressed over a smile); yawning' }),
    body: body('a bulky, scuffed pressure suit with its metal neck ring showing (helmet OFF)', ['A small photograph tucked into the sleeve, as a separate piece'], { upper: 'Bulky suit upper arms, left and right', fore: 'Bulky suit forearms with metal wrist rings, left and right, each in two angles: lying along the table, and raised' }),
    hands: hands('Bare hands (suit gloves off)', ['Left forearm and hand raised to eye level with the oxygen gauge on the wrist (this one piece keeps its forearm)', 'Hand holding a small photograph']),
    props: ['The round suit helmet sitting on the table, visor reflecting light', 'The wrist oxygen gauge: the gauge face alone, and its needle as a separate piece', 'A small worn photograph'],
    note: 'No flags, no agency patches, no real insignia anywhere.',
  },
  blackbeard: {
    face: face({ hair: ['Hair under the hat as a separate piece', 'The huge black beard as a separate piece, covering most of the lower face', 'Four loose ribbon-tied beard braids as separate pieces, so they can sway'],
      mouths: 'mostly hidden by the beard, so only what shows through it: closed; talking; laughing too loud (wide open); snarling with teeth',
      extra: ['Broad black hat as a separate piece', 'Slow-match fuses poking from under the hat brim (left and right), each in 3 states: dull, smouldering, glowing bright', 'Curls of smoke as separate pieces, 3 sizes'] }),
    body: body('a heavy dark coat', ['Sling of pistols across the chest as a separate piece']),
    hands: hands('Hands, big and scarred', ['Hand stroking a braid of the beard', 'Hand holding a flintlock pistol', 'Hand setting a pistol down flat on the table']),
    props: ['A flintlock pistol, lying flat', 'The same pistol held upright'],
  },
  caesar: {
    face: face({ hair: ['Thinning hair over a high forehead as a separate piece'], mouthsExtra: 'a knowing closed smile, like a man counting votes',
      extra: ['Laurel wreath as a separate piece, in 3 angles: straight, worn low at the front, tilted to one side'] }),
    body: body('a toga with a broad purple border', ['The toga drape over the left shoulder as a separate front layer']),
    hands: hands('Hands', ['Hand with fingers drumming (two versions: first and third fingers raised; second and fourth raised)', 'Hand raised adjusting a wreath at the temple', 'Hand with index finger raised, dictating', 'Fingertips rubbing the temple']),
    props: [],
  },
  cerberus: {
    face: [
      'Three separate heads — left, middle and right — each on its own thick neck, black and short-coated, heavy in the jaw: the left head angled a little left, the middle facing forward, the right angled a little right. Each head drawn WITHOUT its lower jaw and WITHOUT ears',
      'Lower jaws (they fit any of the three heads), each a separate piece: closed; open, panting, tongue out; yawning wide; snarling, lips curled back from the teeth; growling (lips half curled)',
      'Ears (fit any head), left and right, in 3 positions: up and alert, back, flat',
      'Eyes that fit any of the heads, each a WHOLE eye (white, iris and lid together), near and far (they differ in three-quarter view): open; half-closed (sleepy); closed (asleep); narrowed; wide open',
      'Nose pieces: normal, and nostrils flared (sniffing)',
    ],
    body: [
      'Massive black body and chest with NO heads and NO front legs, sitting upright at the table like a person, cut off at the table line, three neck stumps showing',
      'A low ridge of small snakes along the neck and spine: 6 small snakes as separate pieces, each in 2 poses (lying flat, raised)',
      'Front legs (shoulder to paw), left and right, each in two angles: lying along the table, and raised',
    ],
    hands: hands('Big front paws with blunt claws (no fingers), each with a short stub of the leg, cut straight across. Draw each pose ONCE, as the right paw: the game mirrors it for the left.', ['A hind paw raised, scratching (as if behind an ear)'], ['flat on the table, relaxed', 'tapping the table (checking)', 'pushing forward (as if pushing chips; chips NOT drawn)', 'shoving forward hard (all in)', 'sweeping sideways (folding)', 'curled, raking toward the body (collecting a pot)', 'resting, curled under']),
    props: ['Three iron collars, each a separate piece sized to one neck', 'One heavy chain linking them, as 3 separate lengths'],
  },
  cyclops: {
    face: face({ hair: ['Shaggy black hair as a separate piece', 'Shaggy black beard as a separate piece'],
      brows: 'One heavy single brow across the forehead, as a separate piece in 4 poses: neutral, raised, furrowed (angry), worried',
      eyesItem: 'ONE great eye in the middle of the brow, each a WHOLE eye (white, iris and lid together), NOT mirrored: looking at the viewer; looking toward the table\'s centre; looking down; looking away; wide open; half-closed; narrowed; closed (a very slow blink)',
      nose: 'Nose in 2 versions: normal, and nostrils flared (sniffing the air)',
      extra: ['The old burn scar around the eye as a separate overlay piece'] }),
    body: body('enormous shoulders and chest, filling the frame', ['Sheepskin over the shoulders as a separate layer']),
    hands: hands('Huge hands', ['Fist raised high (about to thump)', 'Fist coming down hard on the table', 'Hand counting on its fingers: 1, 2, 3 and 4 fingers up (4 pieces)', 'Thumb scratching (as if at the beard)']),
    props: ['His club of green olive wood, leaning upright'],
  },
  davy_jones: {
    face: face({ head: 'Blank head: grey, drowned skin, with ears and neck, NO eyes, eyebrows, nose or mouth drawn on it',
      hair: ['Sodden grey beard (plainly hair, never tentacles) as a separate piece', 'Wet hair under the hat as a separate piece'],
      eyes: 'pale and round, catching the light; he rarely blinks',
      mouthsExtra: 'humming under his breath (lips barely parted)',
      extra: ['Broad hat as a separate piece, brim shedding a thin thread of water', 'A dark shadow overlay that covers the upper half of the face under the brim'] }),
    body: body('hunched, in a long, waterlogged sea-coat', ['Strands of seaweed caught in the folds, 4 separate pieces', 'One extra forearm with the sleeve visibly dripping']),
    hands: hands('Grey, wet hands', ['Hand wringing out the beard', 'Fingers drumming (like rain on a deck)']),
    props: ['Water droplets, 5 sizes', 'A thin falling trickle of water', 'A small puddle on the felt', 'A small crab in 3 poses: climbing, walking sideways, claws raised'],
  },
  death: {
    face: [
      'A plain skull, calm and tired, drawn like a woodcut: NO glowing eyes, NO grin or leer. The cranium WITHOUT the lower jaw, as one piece',
      'The lower jaw alone, in 3 positions: closed, slightly open, open (speaking)',
      'The hood of his black robe, purple-lined: the back of the hood (the dark inside) and the front rim of the hood as separate pieces',
      'A soft shadow overlay that covers half of the skull from the hood',
    ],
    body: body('tall and narrow, in a black hooded robe with a deep purple lining, ragged at the hems, crossed with leather straps, a gold skull brooch at the collarbone; tired posture, leaning forward on the forearms', [], { upper: 'Upper arms in wide robe sleeves, left and right', fore: 'Forearms in wide robe sleeves, left and right, each in two angles: resting on the table, and raised' }),
    hands: hands('Long bone hands (skeleton), seen front-on from across the table, slightly from above, each WITH a short stub of the robe sleeve, cut straight across. Every card is face DOWN, showing his black-and-gold skull card back, at the same size as the cards on his props sheet; a card face that shows is BLANK cream, since the game draws the faces.', [
      'Both hands riffle-shuffling: the deck split in two halves, thumbs lifting the corners, cards interleaving in the middle (one piece)',
      'Both hands bridging the shuffle: the cards arched and springing back together (one piece)',
      'Both hands squaring the deck on the table, fingers tapping its edges (one piece)',
      'Right hand cutting the deck: lifting the top half off the bottom half',
      'Right hand spreading the deck in a ribbon of overlapping face-down cards',
      'Right hand sweeping a small untidy pile of face-down cards toward himself',
    ], [
      'left hand holding the squared deck in a dealer\'s grip: deck in the palm, thumb along the top edge',
      'the same hand, its thumb pushing the top card halfway off the deck',
      'right hand pinching one card between thumb and fingers, ready to deal',
      'right hand flicking a card forward, toward the viewer, the card just leaving the fingers',
      'right hand sliding a card away to the viewer\'s left, arm reaching',
      'right hand sliding a card away to the viewer\'s right, arm reaching',
      'right hand turning a card over, the card on its edge mid-flip, its face blank cream',
      'left hand holding the deck, resting on the table, idle',
    ]),
    props: ['The deck, squared, face down', 'The deck split into two halves', 'A single card back (plain, dark design)'],
    angle: 'front',
    note: 'Death has NO tells: nothing on him should suggest mood, so no angry, surprised or laughing faces, and never glowing eyes. No scythe, hourglass or book at the table. Must not resemble Pratchett\'s Death, Bergman\'s Seventh Seal or Gaiman\'s Death.',
  },
  dracula: {
    face: face({ head: 'Blank head: extreme pallor, pointed ears and neck, NO eyes, eyebrows, nose or mouth drawn on it (skip if you are keeping the existing parts)',
      hair: ['Hair as a separate piece', 'The long white moustache drooping past the chin as a separate piece'],
      brows: 'Massive eyebrows that almost meet over the nose, near and far (they differ in three-quarter view), in 3 clearly different shapes: neutral; angry (inner end pulled down); worried (inner end pushed up). His tell, one brow raised, is done by moving it',
      nose: 'Thin, high-bridged nose as a separate piece',
      mouthsExtra: 'smiling without showing his teeth; a losing face (lips drawn thin, jaw set); all with very red lips, the talking mouths showing sharp white teeth' }),
    body: body('tall and thin, in black without a speck of colour', ['Cape: back layer and front edges as separate pieces']),
    hands: hands('Pale, long-fingered hands with long nails', ['Both hands with fingertips steepled together (one piece)', 'Hand holding the chalice', 'Hand lifting the chalice to sip', 'Hand running one long fingernail along the table']),
    props: ['A dark, heavy chalice, upright', 'The same chalice tilted, as if drinking'],
    note: 'Parts already exist in art-tools/dracula_parts, in an older, glossier style than FDR. Gaps there: the chalice, a talking mouth set, a losing face, and whole-eye swaps (his eyes have fixed pupils). If FDR\'s style is the house style, redo all of his sheets.',
  },
  fdr: {
    face: face({ hair: ['Grey swept-back hair as a separate piece'],
      mouthsExtra: 'a mouth gripping a cigarette holder in the teeth, smiling around it (holder NOT drawn)',
      extra: [`Pince-nez with its cord, as a separate piece, ${CLEAR}`] }),
    body: body('a dark three-piece suit with a white shirt and dark tie', ['Naval cape: the back layer, and the left and right front drapes, as separate pieces']),
    hands: hands('Hands', ['Hand holding a long cigarette holder near the mouth', 'Index finger tapping the holder (tapping ash)', 'Fingers adjusting the pince-nez']),
    props: ['The long cigarette holder alone, cigarette lit at the tip', 'A flake of ash', 'Wisps of smoke, 3 sizes'],
  },
  green_knight: {
    face: face({ head: 'Blank head: GREEN skin, with ears and neck, NO eyes, eyebrows, nose or mouth drawn on it',
      hair: ['Green hair to the shoulders: back layer and front strands as separate pieces', 'Great bush of green beard as a separate piece'],
      mouthsExtra: 'a huge booming laugh (head thrown back, mouth wide open)' }),
    body: body('enormous, broad as a door, in green clothes worked with gold, NO armour', ['Patches of moss creeping on the sleeve: 3 separate pieces, small to large']),
    hands: hands('Huge green hands', ['Thumb running along the edge of an axe head (axe NOT drawn)', 'Hand resting on a holly branch (branch NOT drawn)']),
    props: ['A holly branch, still', 'The same holly branch with its leaves shaking (rustling)', 'His great axe, leaning upright'],
  },
  grey_alien: {
    face: [
      'A huge smooth grey head on a thin neck, shaped like an upturned teardrop, WITHOUT eyes or mouth drawn',
      'Its enormous black almond eyes with no whites, each a WHOLE eye, near and far (they differ in three-quarter view), in 3 states: open; a translucent inner eyelid half across, closing SIDEWAYS; closed sideways',
      'Small slit nostrils as a separate piece',
      'A small lipless mouth, ONE piece only (it never moves)',
    ],
    body: body('narrow grey shoulders and a thin torso, no clothes', [], { upper: 'Thin grey upper arms, left and right', fore: 'Thin grey forearms, left and right, each in two angles: lying along the table, and raised' }),
    hands: hands('Long thin grey fingers', ['Hand with long fingers splayed wide on the table', 'One fingertip touching the table, as if it had never seen wood']),
    props: [],
    note: 'It carries nothing.',
  },
  headless_horseman: {
    face: [
      'NO head. The top of a high coat collar, open, dark inside, with no neck visible',
      'A carved pumpkin with a plain, simple face (NOT a leering or flaming grin), with its cut-out face holes empty',
      'A glow layer that fills the pumpkin\'s carved holes, in 3 intensities: dim, normal, bright',
      'A candle flame in 4 states: normal, tall and bright, small and guttering, out',
      'A soft orange halo of light around the pumpkin, 2 sizes',
    ],
    body: body('huge and square-shouldered, a Hessian trooper\'s coat under a heavy riding cloak', ['Riding cloak: back layer and front edges as separate pieces', 'Cavalry sword in its scabbard as a separate piece'], { upper: 'Upper arms in the coat sleeve, left and right', fore: 'Forearms, left and right, each in two angles: lying along the table, and raised' }),
    hands: hands('Leather riding gauntlets', ['Gauntlet drumming its fingers on the table', 'Both gauntlets holding a pumpkin between them, settling it (pumpkin NOT drawn)']),
    props: [],
  },
  javert: {
    face: face({ hair: ['Enormous side-whiskers climbing toward the nose: left and right as separate pieces'],
      nose: 'A flat nose with deep nostrils as a separate piece',
      mouths: 'neutral closed (his usual); a thin, tight line; talking "ah"; talking "oh"; lips pressed; a slight frown; teeth clenched',
      eyes: 'a hard stare that rarely blinks: make "wide open" his unblinking stare',
      extra: ['Hat with the brim worn low, as a separate piece'] }),
    body: body('a long greatcoat', ['The greatcoat\'s high collar in 2 states: buttoned to the chin, and top buttons undone', 'The stock (neckcloth) as a separate piece']),
    hands: hands('Hands', ['Fingers doing up the top collar button', 'Hand holding a small black notebook', 'Hand with a very slight shake (draw it twice, a hair apart)', 'Hand gripping the top of a cane']),
    props: ['A small black notebook, closed and open', 'The top of a cane'],
  },
  kidd: {
    face: face({ hair: ['Full-bottomed wig: back layer and front curls as separate pieces'], mouthsExtra: 'chewing his lip',
      extra: ['Plain three-cornered hat as a separate piece', 'The whole head turned in three-quarter view, glancing over his shoulder, as one extra piece'] }),
    body: body('a good broadcloth coat buttoned high', ['Cravat in 2 states: neat, and loosened at the throat', 'The corner of a folded paper peeking from the inside pocket, as a separate piece']),
    hands: hands('Hands', ['Hand patting the coat chest', 'Hand rubbing the back of the neck', 'Hand tipping the hat brim', 'Thumb rubbing the fingertips (counting coins that aren\'t there)']),
    props: [],
  },
  lancelot: {
    face: face({ hair: ['A fall of dark hair in 3 separate positions: falling forward, tossed back, mid-toss'], mouthsExtra: 'a sigh (lips parted, bored)' }),
    body: body('polished plate at the shoulders over a bright surcoat', ['Left and right shoulder plates as separate pieces', 'Sword belt as a separate piece']),
    hands: hands('Hands, each with a short stub of sleeve, cut straight across the stub; the forearm piece goes under it. The RIGHT hand is in a polished steel gauntlet, the LEFT is bare: draw every pose for BOTH hands, since they differ.', ['Left hand polishing the right gauntlet with a cloth', 'Right gauntlet held up, admiring it']),
    props: ['A polishing cloth', 'A bright highlight glint for the gauntlet, as an overlay'],
  },
  leonidas: {
    face: face({ hair: ['Long hair as a separate piece', 'Full beard as a separate piece'],
      nose: 'Nose in 2 versions: normal, and nostrils flared (exhaling hard)',
      mouthsExtra: 'open disdain (one corner of the mouth pulled down)' }),
    body: body('a bronze breastplate', ['Red cloak: back layer and front edges as separate pieces']),
    hands: hands('Hands, heavy and scarred', ['Both fists planted on the table, knuckles down (two pieces)', 'Hands with fingers interlaced and pushed out (cracking knuckles, one piece)', 'Hand tugging a cloak straight']),
    props: ['The bronze Corinthian helmet with its tall horsehair crest, sitting on the table in side view'],
  },
  lincoln: {
    face: face({ head: 'Blank head: long and narrow, hollow cheeks under high cheekbones, ears of natural size, neck, and his chin beard along the jaw (NO moustache) painted on; NO eyes, eyebrows, nose or mouth drawn on it',
      hair: ['Dark, untidy hair as a separate piece (only its sides and back show under the hat)'], beardPatch: true,
      mouths: 'lower-face patches this time, NOT mouth only: each is the mouth with the chin beard around it, cut straight across just under the nose, so it lays over the painted beard. Thin lips, a clean upper lip. Neutral; slight smile; open smile; broad smile; laughing; talking "ah"; talking "oh"; talking "ee"; lips pressed ("m/b/p"); "f/v"; tight-lipped; nervous; frown; angry grimace',
      eyes: 'deep-set and tired, under a straight brow, NOT a jutting one',
      nose: 'A long, straight, fairly narrow nose as a separate piece',
      mouthsExtra: 'a small, restrained smile',
      extra: ['His stovepipe hat, as worn, in 4 positions: sitting straight; pushed back on his head; tipped forward, brim low (a nod); lifted an inch off his head (tipping it)'] }),
    body: body('a long, lean frame in a black frock coat and a black bow tie'),
    hands: hands('Long, bony hands', ['Hand stroking the chin beard', 'Both long hands folded together (one piece)', 'Fingers rubbing tired eyes', 'Fingers pinching the hat brim (hat NOT drawn)', 'Hand holding the hat by its brim, lifted (hat drawn)']),
    props: [],
    note: 'Build his face from the Brady and Gardner photographs, and keep it dignified: a long, narrow, gaunt face and a kind, tired look. An earlier attempt read as apelike: no heavy jutting brow ridge, no flat or wide nose, no wide lipless mouth, no protruding jaw, no oversized ears. He wears the hat at all times.',
  },
  loki: {
    face: face({ hair: ['Fair hair worn loose: back layer and front strands as separate pieces'],
      eyes: 'sharp', eyesExtra: 'looking ahead with the iris a strange, different colour for a moment (his tell)',
      mouthsExtra: 'a smile using only half his mouth. EVERY mouth has a row of pale, old stitch-scars across both lips' }),
    body: body('a plain wool tunic in ash-grey and rust, lean', ['A short cloak pinned at one shoulder, as a separate layer', 'The cloak pin (brooch) as a separate piece']),
    hands: hands('Restless hands', ['Fingertips touching the lips', 'Knuckles rippling (as if rolling a chip across them)', 'Fingers turning a small game piece over']),
    props: ['A small golden game piece from an old Norse board game', 'A single iridescent fish scale'],
    note: 'Hidden guest: a spoiler. Keep his art out of anything public. No crown, no helmet, no horns, no green-and-gold, no slicked black hair.',
  },
  martian: {
    face: [
      'One great rounded head that is its whole body, oily grey-brown skin, WITHOUT eyes or mouth drawn',
      'Its two enormous dark eyes, each a WHOLE eye, near and far (they differ in three-quarter view), in 3 states: open; half-closed; closed. They blink out of time with each other',
      'A V-shaped mouth in 4 states: closed; quivering, slightly open; open wide; open and dripping',
      'A faint colour-shift overlay for the skin (the same shape, tinted)',
    ],
    body: [
      'A small three-legged brass seat, a cousin of the fighting-machines: the seat\'s back (behind the head) and front rim as separate pieces',
    ],
    hands: hands('Two bunches of eight whip-thin tentacles instead of arms and hands: draw single tentacles as separate pieces, one in each pose below.', [], [
      'hanging loose', 'curled', 'curled tight', 'tip touching the table', 'raised and reaching forward', 'tips tapping in sequence (three together)', 'sweeping sideways (folding)', 'curling inward, raking toward itself (collecting a pot)',
    ]),
    props: [],
    note: 'No brain under glass, no bubble helmet, no green skin, no ray-gun, nothing like Mars Attacks or Marvin the Martian.',
  },
  medusa: {
    face: face({ head: 'Blank head: a young woman\'s, pale, with ears and neck, NO eyes, eyebrows, nose or mouth drawn, and a scalp from which the snakes grow',
      eyes: 'ordinary, calm and heavy-lidded, NOT glowing',
      extra: [
        'Her hair of snakes as 8 separate snakes, each attached at the scalp end: still and upright; in an S-curve; coiled; hissing with jaws open and fangs showing; tongue out tasting the air; two snakes knotted together; one snake nipping another; one snake curled behind the ear',
      ] }),
    body: body('a simple ancient Greek dress (a chiton), pinned at the shoulders'),
    hands: hands('Hands', ['Hand tucking a snake behind her ear (snake NOT drawn)']),
    props: [],
  },
  merlin: {
    face: face({ hair: ['Long, wild grey beard as a separate piece', 'Grey hair as a separate piece (for when the hood is down)'],
      mouthsExtra: 'murmuring a word (lips barely parted)',
      extra: ['Hood of an undyed wool robe, UP: the back of the hood and its front rim as separate pieces', 'The same hood fallen DOWN around the shoulders'] }),
    body: body('lean and tall in a hooded, undyed wool robe'),
    hands: hands('Old, weathered hands', ['Hand gripping a tall staff (staff NOT drawn)', 'Fingers brushing ash from a sleeve']),
    props: ['A rough, knotted staff taller than he is, standing upright', 'A faint glow overlay for the staff, 2 intensities', 'A candle, and its flame in 2 states: upright, and bending the wrong way'],
    note: 'No pointed hat, no stars, no owl.',
  },
  monster: {
    face: face({ head: 'Blank head: yellow skin stretched thin over muscle, with ears and neck, NO eyes, eyebrows, nose or mouth drawn',
      hair: ['Long, lustrous black hair: back layer and front strands as separate pieces'],
      eyes: 'watery, nearly the colour of their sockets',
      mouthsExtra: 'lips moving while reading; all with straight black lips',
      extra: ['The whole head turned slightly away, flinching (from firelight), as one extra piece'] }),
    body: body('enormous, eight feet tall, in a good coat that was never cut for him (sleeves too short)'),
    hands: hands('Very large hands', ['Hand holding a small open book (book NOT drawn)', 'Fingers turning a page', 'Hand setting a book face down', 'Hand gripping the table edge hard', 'Both hands held palms up, being studied']),
    props: ['A small battered book: closed, open, and lying face down'],
    note: 'Nothing from Universal\'s 1931 design: no neck bolts, flat head, green skin, stitches or forehead scar.',
  },
  nemo: {
    face: face({ hair: ['Full dark beard as a separate piece'],
      eyes: 'set rather wide apart',
      mouthsExtra: 'humming a fugue (lips closed, relaxed)',
      extra: ['Flat sea-captain\'s cap as a separate piece'] }),
    body: body('tall and broad-shouldered in severe dark clothes, after the Neuville and Riou engravings'),
    hands: hands('Hands', ['Fingers turning a great pearl (pearl drawn)', 'Hand holding a pocket chronometer', 'Hand sketching with a pencil', 'Fingertip tapping the table']),
    props: ['A great white pearl', 'A glint highlight for the pearl, as an overlay', 'A pocket chronometer, closed and open', 'A small notebook and a pencil'],
    note: 'Nothing from Disney\'s 1954 film.',
  },
  odysseus: {
    face: face({ hair: ['Grizzled curly hair as a separate piece', 'Grizzled curly beard as a separate piece'],
      extra: ['The conical felt sailor\'s cap of Greek vase painting, as a separate piece'] }),
    body: body('broad in the chest and shoulders, a sea-stained cloak', ['Cloak: back layer and front edges as separate pieces']),
    hands: hands('Weathered hands, a heavy gold ring on one finger', ['One hand twisting the ring on the other hand\'s finger', 'Hands wringing water from a cloak hem']),
    props: ['The heavy gold ring alone', 'A glint highlight for the ring, as an overlay'],
  },
  pope: {
    face: face({ head: 'Blank head: heavy and genial, with ears and neck, NO eyes, eyebrows, nose or mouth drawn',
      nose: 'A strong nose as a separate piece', mouthsExtra: 'a benevolent smile; murmuring in Latin (lips barely parted)',
      extra: ['The tall mitre as a separate piece, in 2 angles: straight, and slightly askew'] }),
    body: body('gold-embroidered vestments that swallow the chair, after Pinturicchio\'s fresco', ['Outer vestment as a separate front layer']),
    hands: hands('Soft, ringed hands', ['One hand turning the ring on the other', 'Both hands folded in the lap (one piece)', 'Hand smoothing the robes', 'Hand held up, admiring the ring']),
    props: ['The papal ring alone, oversized', 'A gold flash of light for the ring, as an overlay'],
  },
  robot: {
    face: [
      'A square steel-and-brass head WITHOUT eyes or mouth, front view',
      'The same head turned three-quarters left and three-quarters right (it turns to look at the pot)',
      'Two round lamp eyes as separate pieces, each in 3 states: lit, dim, dark',
      'A speaker-grille mouth in 3 states: dark, lit, lit bars (talking)',
      'Antennae, left and right, each in 3 poses: upright, bent, twitching',
    ],
    body: body('a riveted barrel of a body in brushed steel and brass, worn bright at the joints, with an empty round socket in the chest', [
      'The round chest lamp in 3 states: lit, flickering (half-lit), dark',
      'For the AI (it takes this body later): a chest-sized iris lens that fits the same socket — brass rim, overlapping iris blades, a pale COOL WHITE light behind — in 4 apertures: wide, half, narrow, closed. Never red',
    ], { upper: 'Jointed metal upper arms, left and right', fore: 'Jointed metal forearms, left and right, each in two angles: lying along the table, and raised' }),
    hands: hands('Jointed metal hands with four fingers'),
    props: ['Puffs of steam, 3 sizes'],
    note: 'Nothing like Robby the Robot, Gort or the Lost in Space robot.',
  },
  roosevelt: {
    face: face({ hair: ['Hair as a separate piece', 'Heavy moustache as a separate piece'],
      mouthsExtra: 'the enormous grin, all teeth (these must read small, so 3 versions: grin, bigger grin, biggest grin)',
      extra: [`Round steel-rimmed spectacles as a separate piece, ${CLEAR}`] }),
    body: body('a barrel chest, leaning forward on both elbows, in a dark suit'),
    hands: hands('Hands', ['Hands holding the spectacles and polishing them hard with a handkerchief', 'Fingers drumming on the felt', 'Fingers tugging the moustache', 'Hand holding a pocket watch']),
    props: ['A handkerchief', 'A pocket watch, closed and open'],
  },
  sherlock: {
    face: face({ head: 'Blank head: long, thin, high-foreheaded, with ears and neck, NO eyes, eyebrows, nose or mouth drawn',
      hair: ['Dark hair, swept back, as a separate piece'], nose: 'A hawk nose as a separate piece',
      mouthsExtra: 'gripping a pipe stem in the teeth (pipe NOT drawn)' }),
    body: body('very thin, in a dark frock coat, after Sidney Paget'),
    hands: hands('Long, thin hands', ['Both hands with fingertips together (one piece)', 'Hand holding a pipe', 'Hand tapping a pipe stem against the teeth', 'Hand turning a magnifying lens']),
    props: ['A straight black clay pipe (NOT a curved calabash)', 'Puffs of pipe smoke, 3 sizes', 'A magnifying lens'],
    note: 'No deerstalker, no calabash pipe, nothing from modern screen versions.',
  },
  silver: {
    face: face({ head: 'Blank head: big, pale, with ears and neck, NO eyes, eyebrows, nose or mouth drawn',
      hair: ['Hair tied back as a separate piece'] }),
    body: body('very tall and broad, a cook\'s apron over a sailor\'s coat', ['The top of a crutch tucked under one arm, as a separate piece']),
    hands: hands('Big, easy hands', ['Finger stroking a parrot\'s head (parrot NOT drawn)', 'Hands wiping on the apron', 'Hand rapping a crutch']),
    props: [
      'Captain Flint, the parrot, WITHOUT her head: perched upright; leaning sideways (sidling); hunched (preening)',
      'The parrot\'s head: beak closed; beak wide open (squawking); turned into her feathers (preening)',
      'The parrot\'s wings: folded; half open; spread',
    ],
  },
  socrates: {
    face: face({ head: 'Blank head: a bald dome, with ears and neck, NO eyes, eyebrows, nose or mouth drawn',
      hair: ['Big untidy beard as a separate piece'], nose: 'A snub nose as a separate piece',
      eyes: 'wide and bulging',
      mouthsExtra: 'smiling as if at a private joke' }),
    body: body('a short, thick body in one plain, shabby cloak'),
    hands: hands('Hands', ['Fingertip scratching the nose', 'Hand holding a shallow wine cup', 'Hands pulling a cloak tighter', 'Fingers scratching the beard']),
    props: ['A shallow wine cup, full and empty'],
  },
  spartacus: {
    face: face({ hair: ['Cropped hair as a separate piece'], nose: 'A nose broken more than once, as a separate piece' }),
    body: body('broad, bare shoulders under a rough Thracian cloak', ['Cloak: back layer and front edges as separate pieces'], { upper: 'Bare, muscled upper arms, left and right', fore: 'Bare forearms, left and right, each in two angles: lying along the table, and raised; the LEFT wrist carries a pale band of shackle scar' }),
    hands: hands('Heavy, scarred hands', ['One hand rubbing the scar on the other wrist', 'Hands flexing, fingers spread', 'Both hands gripping the table edge']),
    props: ['The pale shackle-scar band alone, as an overlay'],
    note: 'No gladiator helmet, nothing from the 1960 film or the TV series.',
  },
  the_ai: {
    face: [
      'A single lens set in a ceiling: its brass rim as a separate piece',
      'Overlapping iris blades in 4 apertures: wide open, half, narrow, almost closed',
      'The pale, cool WHITE light behind the iris, as a separate piece',
      'A soft white halo of light, 2 intensities',
    ],
    body: null, hands: null, props: null,
    faceTitle: 'Sheet 1 — The lens',
    portrait: 'Stylised 2D illustration for a poker video game, painterly but clean with flat readable shapes, matching the rest of the cast. Looking up at the ceiling of an old space station at night: a single round lens set into the ceiling panels, a brass-rimmed iris of overlapping blades with a pale, cool white light behind it. Calm, watchful, faintly unsettling. No face, no text, no logos, no watermark. Never red.',
    note: 'Before the turn it has no body; after it, it wears the Robot, whose sheets include the chest lens. Never red, nothing like HAL 9000.',
  },
  van_helsing: {
    face: face({ head: 'Blank head: clean-shaven, square-jawed, broad forehead, with ears and neck, NO eyes, eyebrows, nose or mouth drawn',
      hair: ['Reddish hair swept back as a separate piece'],
      brows: 'Bushy eyebrows near and far (they differ in three-quarter view), in 3 clearly different shapes: neutral; angry (inner end pulled down); worried (inner end pushed up)',
      eyes: 'wide-set and blue',
      mouthsExtra: 'muttering (lips barely parted)',
      extra: [`Spectacles as a separate piece, ${CLEAR}`] }),
    body: body('square and solid, a deep chest in a plain black professor\'s frock coat', ['A small crucifix at the collar as a separate piece']),
    hands: hands('Hands', ['Hands holding the spectacles and polishing them on a big white handkerchief', 'Fingers touching a crucifix at the collar', 'Hand writing in a diary with a pen']),
    props: ['A big white handkerchief', 'A leather diary, closed and open, and a pen', 'A doctor\'s bag'],
  },
  washington: {
    face: face({ head: 'Blank head: long and heavy-jawed, with ears and neck, NO eyes, eyebrows, nose or mouth drawn',
      hair: ['His own hair, powdered and tied at the nape with a ribbon (not a wig), as a separate piece'],
      mouths: 'neutral, set firm (his usual); a slight smile; talking "ah"; talking "oh"; talking "ee"; lips pressed; frown; tight-lipped; jaw working (lips pressed, cheek tensed)' }),
    body: body('the straightest back at the table, in a buff-and-blue general\'s coat with a high collar', ['Gold epaulettes, left and right, as separate pieces', 'Buff waistcoat as a separate front layer', 'Coat cuffs, left and right, as separate pieces']),
    hands: hands('Hands', ['One hand straightening the cuff on the other wrist', 'Hands squaring the edges of a stack (stack NOT drawn)', 'Hand smoothing a waistcoat']),
    props: [],
  },
  wolf_man: {
    face: [
      'A real wolf\'s head (long muzzle) on a man\'s neck, grey-brown fur, drawn WITHOUT its ears, its lower jaw or its eyes',
      'Tall pointed ears, left and right, each in 3 positions: up, back, flat',
      'The lower jaw in 5 states: closed; open, talking; snarling (lips curled back from the teeth); growling (half curled); panting',
      eyes('a man\'s tired eyes'),
      'Fur brow ridges, near and far, in 3 clearly different shapes: neutral; angry; worried',
      'Nose: normal, and nostrils flared (sniffing)',
    ],
    body: body('a big man\'s frame in the remains of a good shirt and waistcoat split at the seams, fur showing through'),
    hands: hands('Furred hands with claws', ['Claws scraping the felt (fingers curled, claws down)', 'Hand scratching behind an ear']),
    props: ['Tufts of shed fur, 3 pieces'],
    note: 'Not a hairy man\'s face: that is the Universal film\'s design. "The Wolf Man" as a name is still an open decision.',
  },
};
